//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//	   classes e:ISSUE l:CS 	
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable=false)]
public partial class ISSUE {
    
    private string iD_ACCESSIONField;
    
    private string jS_JOURNALSEQField;
    
    private string yR_PUBLYEARField;
    
    private ITEM[] iTEMField;
    
    private string iSSUENOField;
    
    /// <remarks/>
    public string ID_ACCESSION {
        get {
            return this.iD_ACCESSIONField;
        }
        set {
            this.iD_ACCESSIONField = value;
        }
    }
    
    /// <remarks/>
    public string JS_JOURNALSEQ {
        get {
            return this.jS_JOURNALSEQField;
        }
        set {
            this.jS_JOURNALSEQField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string YR_PUBLYEAR {
        get {
            return this.yR_PUBLYEARField;
        }
        set {
            this.yR_PUBLYEARField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ITEM")]
    public ITEM[] ITEM {
        get {
            return this.iTEMField;
        }
        set {
            this.iTEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string ISSUENO {
        get {
            return this.iSSUENOField;
        }
        set {
            this.iSSUENOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITEM {
    
    private ITEM_CONTENT iTEM_CONTENTField;
    
    private string iTEMNOField;
    
    /// <remarks/>
    public ITEM_CONTENT ITEM_CONTENT {
        get {
            return this.iTEM_CONTENTField;
        }
        set {
            this.iTEM_CONTENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string ITEMNO {
        get {
            return this.iTEMNOField;
        }
        set {
            this.iTEMNOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ITEM_CONTENT {
    
    private DT_DOCUMENTTYPE dT_DOCUMENTTYPEField;
    
    private string pG_PAGESPANField;
    
    private string mA_MEETINGABSTRACTField;
    
    private LA_LANGUAGE[] lA_LANGUAGEField;
    
    private KEYWORD[] kEYWORDField;
    
    private TITLES tITLESField;
    
    private AI_ARTICLEIDENTIFIER[] aI_ARTICLEIDENTIFIERField;
    
    private CI_CITATION[] cI_CITATIONField;
    
    private ABSTRACT1[] aBSTRACTField;
    
    private BIOSIS_DATA bIOSIS_DATAField;
    
    private FUNDING_ACKNOWLEDGEMENT fUNDING_ACKNOWLEDGEMENTField;
    
    /// <remarks/>
    public DT_DOCUMENTTYPE DT_DOCUMENTTYPE {
        get {
            return this.dT_DOCUMENTTYPEField;
        }
        set {
            this.dT_DOCUMENTTYPEField = value;
        }
    }
    
    /// <remarks/>
    public string PG_PAGESPAN {
        get {
            return this.pG_PAGESPANField;
        }
        set {
            this.pG_PAGESPANField = value;
        }
    }
    
    /// <remarks/>
    public string MA_MEETINGABSTRACT {
        get {
            return this.mA_MEETINGABSTRACTField;
        }
        set {
            this.mA_MEETINGABSTRACTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LA_LANGUAGE")]
    public LA_LANGUAGE[] LA_LANGUAGE {
        get {
            return this.lA_LANGUAGEField;
        }
        set {
            this.lA_LANGUAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KEYWORD")]
    public KEYWORD[] KEYWORD {
        get {
            return this.kEYWORDField;
        }
        set {
            this.kEYWORDField = value;
        }
    }
    
    /// <remarks/>
    public TITLES TITLES {
        get {
            return this.tITLESField;
        }
        set {
            this.tITLESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AI_ARTICLEIDENTIFIER")]
    public AI_ARTICLEIDENTIFIER[] AI_ARTICLEIDENTIFIER {
        get {
            return this.aI_ARTICLEIDENTIFIERField;
        }
        set {
            this.aI_ARTICLEIDENTIFIERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CI_CITATION")]
    public CI_CITATION[] CI_CITATION {
        get {
            return this.cI_CITATIONField;
        }
        set {
            this.cI_CITATIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ABSTRACT")]
    public ABSTRACT1[] ABSTRACT {
        get {
            return this.aBSTRACTField;
        }
        set {
            this.aBSTRACTField = value;
        }
    }
    
    /// <remarks/>
    public BIOSIS_DATA BIOSIS_DATA {
        get {
            return this.bIOSIS_DATAField;
        }
        set {
            this.bIOSIS_DATAField = value;
        }
    }
    
    /// <remarks/>
    public FUNDING_ACKNOWLEDGEMENT FUNDING_ACKNOWLEDGEMENT {
        get {
            return this.fUNDING_ACKNOWLEDGEMENTField;
        }
        set {
            this.fUNDING_ACKNOWLEDGEMENTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DT_DOCUMENTTYPE {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Abstract of Published Item")]
    AbstractofPublishedItem,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Art Exhibit Review")]
    ArtExhibitReview,
    
    /// <remarks/>
    Article,
    
    /// <remarks/>
    Bibliography,
    
    /// <remarks/>
    Biographical,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Book Review")]
    BookReview,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CC Meeting Abstract")]
    CCMeetingAbstract,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CC Meeting Heading")]
    CCMeetingHeading,
    
    /// <remarks/>
    Chronology,
    
    /// <remarks/>
    Correction,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Dance Performance Review")]
    DancePerformanceReview,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Database Review")]
    DatabaseReview,
    
    /// <remarks/>
    Discussion,
    
    /// <remarks/>
    Editorial,
    
    /// <remarks/>
    Excerpt,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Fiction, Creative Prose")]
    FictionCreativeProse,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Film Review")]
    FilmReview,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Hardware Review")]
    HardwareReview,
    
    /// <remarks/>
    Letter,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Main Cite")]
    MainCite,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Meeting Abstract")]
    MeetingAbstract,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Meeting Summary")]
    MeetingSummary,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Music Performance Review")]
    MusicPerformanceReview,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Music Score")]
    MusicScore,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Music Score Review")]
    MusicScoreReview,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("News Item")]
    NewsItem,
    
    /// <remarks/>
    Note,
    
    /// <remarks/>
    Patent,
    
    /// <remarks/>
    Poetry,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Press Digest")]
    PressDigest,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Proceedings Paper")]
    ProceedingsPaper,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Record Review")]
    RecordReview,
    
    /// <remarks/>
    Reprint,
    
    /// <remarks/>
    Review,
    
    /// <remarks/>
    Script,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Software Review")]
    SoftwareReview,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("TV Review, Radio Review")]
    TVReviewRadioReview,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Theater Review")]
    TheaterReview,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class LA_LANGUAGE {
    
    private string seqField;
    
    private LANGUAGE valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public LANGUAGE Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
public enum LANGUAGE {
    
    /// <remarks/>
    Afrikaans,
    
    /// <remarks/>
    Albanian,
    
    /// <remarks/>
    Amharic,
    
    /// <remarks/>
    Arabic,
    
    /// <remarks/>
    Armenian,
    
    /// <remarks/>
    Assamese,
    
    /// <remarks/>
    Azerbaijani,
    
    /// <remarks/>
    Basque,
    
    /// <remarks/>
    Belorussian,
    
    /// <remarks/>
    Balinese,
    
    /// <remarks/>
    Bengali,
    
    /// <remarks/>
    Bulgarian,
    
    /// <remarks/>
    Burmese,
    
    /// <remarks/>
    Byelorussian,
    
    /// <remarks/>
    Cambodian,
    
    /// <remarks/>
    Cree,
    
    /// <remarks/>
    Chinese,
    
    /// <remarks/>
    Croatian,
    
    /// <remarks/>
    Catalan,
    
    /// <remarks/>
    Czech,
    
    /// <remarks/>
    Danish,
    
    /// <remarks/>
    Dutch,
    
    /// <remarks/>
    English,
    
    /// <remarks/>
    Esperanto,
    
    /// <remarks/>
    Eskimo,
    
    /// <remarks/>
    Estonian,
    
    /// <remarks/>
    Faeroese,
    
    /// <remarks/>
    Farsi,
    
    /// <remarks/>
    Fijian,
    
    /// <remarks/>
    Finnish,
    
    /// <remarks/>
    Flemish,
    
    /// <remarks/>
    French,
    
    /// <remarks/>
    Frisian,
    
    /// <remarks/>
    Gaelic,
    
    /// <remarks/>
    Galician,
    
    /// <remarks/>
    German,
    
    /// <remarks/>
    Greek,
    
    /// <remarks/>
    Georgian,
    
    /// <remarks/>
    Gujarati,
    
    /// <remarks/>
    Hawaiian,
    
    /// <remarks/>
    Hebrew,
    
    /// <remarks/>
    Hindi,
    
    /// <remarks/>
    Hungarian,
    
    /// <remarks/>
    Icelandic,
    
    /// <remarks/>
    Indonesian,
    
    /// <remarks/>
    Interlingua,
    
    /// <remarks/>
    Irish,
    
    /// <remarks/>
    Italian,
    
    /// <remarks/>
    Japanese,
    
    /// <remarks/>
    Javanese,
    
    /// <remarks/>
    Kannada,
    
    /// <remarks/>
    Kazakh,
    
    /// <remarks/>
    Kirghiz,
    
    /// <remarks/>
    Kinyarwanda,
    
    /// <remarks/>
    Korean,
    
    /// <remarks/>
    Kashmiri,
    
    /// <remarks/>
    Latin,
    
    /// <remarks/>
    Latvian,
    
    /// <remarks/>
    Letzeburgesh,
    
    /// <remarks/>
    Lithuanian,
    
    /// <remarks/>
    Laotian,
    
    /// <remarks/>
    Lappish,
    
    /// <remarks/>
    Macedonian,
    
    /// <remarks/>
    Malay,
    
    /// <remarks/>
    Mongolian,
    
    /// <remarks/>
    Malayalam,
    
    /// <remarks/>
    Marathi,
    
    /// <remarks/>
    Moldavian,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Malayo-Polynesian")]
    MalayoPolynesian,
    
    /// <remarks/>
    Maori,
    
    /// <remarks/>
    Malagasy,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Multi-Language")]
    MultiLanguage,
    
    /// <remarks/>
    Norwegian,
    
    /// <remarks/>
    Nepali,
    
    /// <remarks/>
    Ojibwa,
    
    /// <remarks/>
    Panjabi,
    
    /// <remarks/>
    Persian,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Pidgin English")]
    PidginEnglish,
    
    /// <remarks/>
    Polish,
    
    /// <remarks/>
    Papiamento,
    
    /// <remarks/>
    Provencal,
    
    /// <remarks/>
    Portuguese,
    
    /// <remarks/>
    Pushto,
    
    /// <remarks/>
    Quechua,
    
    /// <remarks/>
    Romansch,
    
    /// <remarks/>
    Rumanian,
    
    /// <remarks/>
    Russian,
    
    /// <remarks/>
    Sanskrit,
    
    /// <remarks/>
    Serbian,
    
    /// <remarks/>
    Sinhalese,
    
    /// <remarks/>
    Sindhi,
    
    /// <remarks/>
    Slovak,
    
    /// <remarks/>
    Slovene,
    
    /// <remarks/>
    Slovenian,
    
    /// <remarks/>
    Samoan,
    
    /// <remarks/>
    Spanish,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Serbo-Croatian")]
    SerboCroatian,
    
    /// <remarks/>
    Swedish,
    
    /// <remarks/>
    Swahili,
    
    /// <remarks/>
    Swazi,
    
    /// <remarks/>
    Tadzhik,
    
    /// <remarks/>
    Tagalog,
    
    /// <remarks/>
    Thai,
    
    /// <remarks/>
    Tibetan,
    
    /// <remarks/>
    Turkish,
    
    /// <remarks/>
    Tamil,
    
    /// <remarks/>
    Turkmen,
    
    /// <remarks/>
    Ukrainian,
    
    /// <remarks/>
    Urdu,
    
    /// <remarks/>
    Uzbek,
    
    /// <remarks/>
    Valencian,
    
    /// <remarks/>
    Vietnamese,
    
    /// <remarks/>
    Welsh,
    
    /// <remarks/>
    Yiddish,
    
    /// <remarks/>
    Zulu,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class KEYWORD {
    
    private string aUTHOR_KEYWORDField;
    
    private string seqField;
    
    /// <remarks/>
    public string AUTHOR_KEYWORD {
        get {
            return this.aUTHOR_KEYWORDField;
        }
        set {
            this.aUTHOR_KEYWORDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TITLES {
    
    private string tI_TITLEField;
    
    private string eT_ENHANCEDTITLEField;
    
    /// <remarks/>
    public string TI_TITLE {
        get {
            return this.tI_TITLEField;
        }
        set {
            this.tI_TITLEField = value;
        }
    }
    
    /// <remarks/>
    public string ET_ENHANCEDTITLE {
        get {
            return this.eT_ENHANCEDTITLEField;
        }
        set {
            this.eT_ENHANCEDTITLEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AI_ARTICLEIDENTIFIER {
    
    private string seqField;
    
    private IDENTIFIER_TYPE typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public IDENTIFIER_TYPE type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
public enum IDENTIFIER_TYPE {
    
    /// <remarks/>
    ARTN,
    
    /// <remarks/>
    DOI,
    
    /// <remarks/>
    PII,
    
    /// <remarks/>
    PMID,
    
    /// <remarks/>
    SICI,
    
    /// <remarks/>
    UNSP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CI_CITATION {
    
    private CI_INFO cI_INFOField;
    
    private FULL_CI_INFO fULL_CI_INFOField;
    
    private string seqField;
    
    private CI_CITATIONType typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    public CI_INFO CI_INFO {
        get {
            return this.cI_INFOField;
        }
        set {
            this.cI_INFOField = value;
        }
    }
    
    /// <remarks/>
    public FULL_CI_INFO FULL_CI_INFO {
        get {
            return this.fULL_CI_INFOField;
        }
        set {
            this.fULL_CI_INFOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CI_CITATIONType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CI_INFO {
    
    private CI_JOURNAL itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CI_JOURNAL")]
    public CI_JOURNAL Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CI_JOURNAL {
    
    private string cI_AUTHORField;
    
    private string cI_VOLUMEField;
    
    private string cI_PAGEField;
    
    private string cI_YEARField;
    
    private string cI_TITLEField;
    
    private CI_IMPLICITINDICATOR cI_IMPLICITINDICATORField;
    
    private bool cI_IMPLICITINDICATORFieldSpecified;
    
    private INDICATOR kEYSAVE_EXPENDEDField;
    
    private bool kEYSAVE_EXPENDEDFieldSpecified;
    
    /// <remarks/>
    public string CI_AUTHOR {
        get {
            return this.cI_AUTHORField;
        }
        set {
            this.cI_AUTHORField = value;
        }
    }
    
    /// <remarks/>
    public string CI_VOLUME {
        get {
            return this.cI_VOLUMEField;
        }
        set {
            this.cI_VOLUMEField = value;
        }
    }
    
    /// <remarks/>
    public string CI_PAGE {
        get {
            return this.cI_PAGEField;
        }
        set {
            this.cI_PAGEField = value;
        }
    }
    
    /// <remarks/>
    public string CI_YEAR {
        get {
            return this.cI_YEARField;
        }
        set {
            this.cI_YEARField = value;
        }
    }
    
    /// <remarks/>
    public string CI_TITLE {
        get {
            return this.cI_TITLEField;
        }
        set {
            this.cI_TITLEField = value;
        }
    }
    
    /// <remarks/>
    public CI_IMPLICITINDICATOR CI_IMPLICITINDICATOR {
        get {
            return this.cI_IMPLICITINDICATORField;
        }
        set {
            this.cI_IMPLICITINDICATORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CI_IMPLICITINDICATORSpecified {
        get {
            return this.cI_IMPLICITINDICATORFieldSpecified;
        }
        set {
            this.cI_IMPLICITINDICATORFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public INDICATOR KEYSAVE_EXPENDED {
        get {
            return this.kEYSAVE_EXPENDEDField;
        }
        set {
            this.kEYSAVE_EXPENDEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KEYSAVE_EXPENDEDSpecified {
        get {
            return this.kEYSAVE_EXPENDEDFieldSpecified;
        }
        set {
            this.kEYSAVE_EXPENDEDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum CI_IMPLICITINDICATOR {
    
    /// <remarks/>
    I,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(" ")]
    Item,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
public enum INDICATOR {
    
    /// <remarks/>
    Y,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FULL_CI_INFO {
    
    private FULL_CI_INFO_TYPE typeField;
    
    private bool tR_Implicit_INDField;
    
    public FULL_CI_INFO() {
        this.tR_Implicit_INDField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FULL_CI_INFO_TYPE type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool TR_Implicit_IND {
        get {
            return this.tR_Implicit_INDField;
        }
        set {
            this.tR_Implicit_INDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
public enum FULL_CI_INFO_TYPE {
    
    /// <remarks/>
    Journal,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Book-Series")]
    BookSeries,
    
    /// <remarks/>
    General,
    
    /// <remarks/>
    UnPublished,
    
    /// <remarks/>
    Thesis,
    
    /// <remarks/>
    Report,
    
    /// <remarks/>
    Patent,
    
    /// <remarks/>
    Meeting,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Magazine-Newspaper")]
    MagazineNewspaper,
    
    /// <remarks/>
    InPress,
    
    /// <remarks/>
    Communication,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Non-Traditional Reference")]
    NonTraditionalReference,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("FCR-EXEMPT")]
    FCREXEMPT,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Social Media")]
    SocialMedia,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Data Repository")]
    DataRepository,
    
    /// <remarks/>
    DCI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum CI_CITATIONType {
    
    /// <remarks/>
    retracted,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ABSTRACT1 {
    
    private string seqField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BIOSIS_DATA {
    
    private BIOSIS_FOREIGN_TITLE[] bIOSIS_FOREIGN_TITLEField;
    
    private string bIOSIS_URLField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BIOSIS_FOREIGN_TITLE")]
    public BIOSIS_FOREIGN_TITLE[] BIOSIS_FOREIGN_TITLE {
        get {
            return this.bIOSIS_FOREIGN_TITLEField;
        }
        set {
            this.bIOSIS_FOREIGN_TITLEField = value;
        }
    }
    
    /// <remarks/>
    public string BIOSIS_URL {
        get {
            return this.bIOSIS_URLField;
        }
        set {
            this.bIOSIS_URLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BIOSIS_FOREIGN_TITLE {
    
    private string seqField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FUNDING_ACKNOWLEDGEMENT {
    
    private FUNDING_TEXT[] fUNDING_TEXTField;
    
    private FUNDING_GRANT_NO[] fUNDING_GRANT_NOField;
    
    private FUNDING_ACKNOWLEDGEMENTFUNDING_ORG_GROUP[] fUNDING_ORG_GROUPField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FUNDING_TEXT")]
    public FUNDING_TEXT[] FUNDING_TEXT {
        get {
            return this.fUNDING_TEXTField;
        }
        set {
            this.fUNDING_TEXTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FUNDING_GRANT_NO")]
    public FUNDING_GRANT_NO[] FUNDING_GRANT_NO {
        get {
            return this.fUNDING_GRANT_NOField;
        }
        set {
            this.fUNDING_GRANT_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FUNDING_ORG_GROUP")]
    public FUNDING_ACKNOWLEDGEMENTFUNDING_ORG_GROUP[] FUNDING_ORG_GROUP {
        get {
            return this.fUNDING_ORG_GROUPField;
        }
        set {
            this.fUNDING_ORG_GROUPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FUNDING_TEXT {
    
    private string seqField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FUNDING_GRANT_NO {
    
    private string seqField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FUNDING_ACKNOWLEDGEMENTFUNDING_ORG_GROUP {
    
    private FUNDING_ORG_NAME fUNDING_ORG_NAMEField;
    
    private FUNDING_ORG_GRANT[] fUNDING_ORG_GRANTField;
    
    private string seqField;
    
    /// <remarks/>
    public FUNDING_ORG_NAME FUNDING_ORG_NAME {
        get {
            return this.fUNDING_ORG_NAMEField;
        }
        set {
            this.fUNDING_ORG_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FUNDING_ORG_GRANT", IsNullable=true)]
    public FUNDING_ORG_GRANT[] FUNDING_ORG_GRANT {
        get {
            return this.fUNDING_ORG_GRANTField;
        }
        set {
            this.fUNDING_ORG_GRANTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FUNDING_ORG_NAME {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FUNDING_ORG_GRANT {
    
    private string grant_no_seqField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string grant_no_seq {
        get {
            return this.grant_no_seqField;
        }
        set {
            this.grant_no_seqField = value;
        }
    }
}
